[project]
name = "fabopsy-attributes"
version = "0.0.2"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.13.3",
]

[dependency-groups]
dev = [
    "build>=1.4.4",
    "jsonschema2md>=1.7.0",
    "twine>=6.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
